version: '3.7'

services:

  server:
    container_name: server
    build: ./server
    ports:
      - 5000:5000

  client:
    container_name: client
    build: ./client
    ports:
      - 3001:3000
    links: 
      - server